/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArIndexRouteImport } from './routes/ar.index'
import { Route as ArProjectRouteImport } from './routes/ar.$project'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArIndexRoute = ArIndexRouteImport.update({
  id: '/ar/',
  path: '/ar/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArProjectRoute = ArProjectRouteImport.update({
  id: '/ar/$project',
  path: '/ar/$project',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ar/$project': typeof ArProjectRoute
  '/ar/': typeof ArIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ar/$project': typeof ArProjectRoute
  '/ar': typeof ArIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ar/$project': typeof ArProjectRoute
  '/ar/': typeof ArIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ar/$project' | '/ar/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ar/$project' | '/ar'
  id: '__root__' | '/' | '/ar/$project' | '/ar/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArProjectRoute: typeof ArProjectRoute
  ArIndexRoute: typeof ArIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ar/': {
      id: '/ar/'
      path: '/ar'
      fullPath: '/ar/'
      preLoaderRoute: typeof ArIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ar/$project': {
      id: '/ar/$project'
      path: '/ar/$project'
      fullPath: '/ar/$project'
      preLoaderRoute: typeof ArProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArProjectRoute: ArProjectRoute,
  ArIndexRoute: ArIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
