import type { ProjectConfig } from "@/models/Project";

/**
 * Project configuration is fully separated from the UI, so the same viewer can
 * serve any number of developments via /ar/$project.
 */
export const projectA: ProjectConfig = {
  slug: "project-a",
  name: "Aurelia Heights",
  developer: "Aurelia Hospitality",
  tagline: "Experience Your Future Home",
  location: "Whitefield, Bengaluru",
  intro:
    "A limited collection of 1, 2 and 3 bedroom residences wrapped around a landscaped podium, two levels of amenities and a rooftop pool.",
  heroImage: "/assets/images/hero.jpg",
  realWorldSize: 0.8,
  modelUrl: "/assets/models/property.glb",
  usdzUrl: "/assets/models/property.usdz",
  arVideoUrl: "/assets/videos/project-film.mp4",
  stats: [
    { label: "Towers", value: "3" },
    { label: "Residences", value: "248" },
    { label: "Open space", value: "72%" },
    { label: "Possession", value: "2028" },
  ],
  gallery: [
    {
      id: "g1",
      src: "/assets/images/gallery-facade.jpg",
      title: "Arrival facade",
      caption: "Evening approach along the lit forecourt.",
    },
    {
      id: "g2",
      src: "/assets/images/gallery-pool.jpg",
      title: "Rooftop pool",
      caption: "Infinity edge pool on level 18.",
    },
    {
      id: "g3",
      src: "/assets/images/gallery-living.jpg",
      title: "Living room",
      caption: "3 BHK corner residence with wrap-around glazing.",
    },
    {
      id: "g4",
      src: "/assets/images/gallery-garden.jpg",
      title: "Podium garden",
      caption: "Two acres of landscaped courtyard.",
    },
  ],
  amenities: [
    {
      id: "a1",
      title: "Rooftop swimming pool",
      description: "25 m infinity pool with a landscaped sun deck and pool lounge.",
      icon: "pool",
      image: "/assets/images/gallery-pool.jpg",
    },
    {
      id: "a2",
      title: "Fitness studio",
      description: "Equipped gym with a separate yoga and functional training deck.",
      icon: "gym",
    },
    {
      id: "a3",
      title: "Clubhouse",
      description: "12,000 sq ft clubhouse with lounge, co-working and private dining.",
      icon: "clubhouse",
    },
    {
      id: "a4",
      title: "Children's play area",
      description: "Shaded play zone with soft flooring and a toddler garden.",
      icon: "play",
    },
    {
      id: "a5",
      title: "Podium garden",
      description: "Two acres of native landscaping, walking loop and reflexology path.",
      icon: "garden",
      image: "/assets/images/gallery-garden.jpg",
    },
    {
      id: "a6",
      title: "Covered parking",
      description: "Two basement levels with EV-ready charging bays.",
      icon: "parking",
    },
    {
      id: "a7",
      title: "24/7 security",
      description: "Gated access, video door phones and perimeter surveillance.",
      icon: "security",
    },
  ],
  floorPlans: [
    {
      id: "fp1",
      name: "1 BHK",
      area: "648 sq ft",
      bedrooms: 1,
      bathrooms: 1,
      balconies: 1,
      description: "Efficient single-bedroom layout with an open kitchen and a full-width balcony.",
      image: "/assets/images/floorplan-1bhk.jpg",
      priceFrom: "From ₹68 L",
    },
    {
      id: "fp2",
      name: "2 BHK",
      area: "1,120 sq ft",
      bedrooms: 2,
      bathrooms: 2,
      balconies: 2,
      description: "Corner residence with a dedicated dining zone and dual-aspect daylight.",
      image: "/assets/images/floorplan-2bhk.jpg",
      priceFrom: "From ₹1.15 Cr",
    },
    {
      id: "fp3",
      name: "3 BHK",
      area: "1,684 sq ft",
      bedrooms: 3,
      bathrooms: 3,
      balconies: 2,
      description: "Wrap-around glazing, utility deck and a private family lounge.",
      image: "/assets/images/floorplan-3bhk.jpg",
      priceFrom: "From ₹1.86 Cr",
    },
  ],
  hotspots: [
    {
      id: "h1",
      label: "Pool",
      title: "Swimming pool",
      description: "Premium rooftop swimming pool with a landscaped deck.",
      position: { x: 0.1, y: 0.3, z: 0 },
    },
    {
      id: "h2",
      label: "Gym",
      title: "Fitness studio",
      description: "Level 3 gym overlooking the podium garden.",
      position: { x: -0.3, y: 0.18, z: 0.2 },
    },
    {
      id: "h3",
      label: "Garden",
      title: "Podium garden",
      description: "Two acres of native landscaping and walking loops.",
      position: { x: 0.38, y: 0.05, z: 0.32 },
    },
    {
      id: "h4",
      label: "Parking",
      title: "Basement parking",
      description: "Two covered levels with EV charging bays.",
      position: { x: -0.42, y: 0.04, z: -0.28 },
    },
    {
      id: "h5",
      label: "Clubhouse",
      title: "Clubhouse",
      description: "Lounge, co-working and private dining across 12,000 sq ft.",
      position: { x: 0.3, y: 0.14, z: -0.32 },
    },
    {
      id: "h6",
      label: "Entrance",
      title: "Grand entrance",
      description: "Double-height lobby with a lit arrival forecourt.",
      position: { x: 0, y: 0.1, z: 0.46 },
    },
  ],
  contact: {
    bookVisitUrl: "https://aurelia-resort.example.com/book-a-visit",
    contactUrl: "https://aurelia-resort.example.com/contact",
    phone: "+919000000000",
    whatsapp: "https://wa.me/919000000000?text=I%27m%20interested%20in%20Aurelia%20Heights",
    shareUrl: "https://aurelia-resort.example.com/ar/project-a",
  },
};
